name: Hydrometer OCR API
slug: hydrometer_ocr
description: OCR backend for ESP32-CAM hydrometer
version: "0.10.3"
panel_icon: mdi:water-percent
panel_title: Hidrômetro
panel_admin: false
arch:
  - amd64

startup: services
boot: auto
host_network: false

ports:
  8000/tcp: 8000

ingress: true
ingress_port: 8000

map:
  - media:rw
  - config:ro

image: ghcr.io/ampaiva/hydrometer_ocr_addon/{arch}

options:
  openai_api_key: ""
  openai_model_default: "gpt-4.1"
  openai_model_secondary: ""
  openai_require_consensus: false
  ocr_entity_id: "sensor.agua_leitura_2"
  ocr_digits: 6
  ocr_max_delta_liters: 300
  ocr_enable_heuristics: true
  esp32_server: "192.168.86.121:8000"
  esp32_capture_interval_min: 30
  esp32_pre_capture_wait_ms: 2_000
  esp32_capture_interval_ms: 1_200_000
  esp32_delay_flash_ms: 120
  framesize: "FRAMESIZE_VGA"
  jpeg_quality: 12
  fb_count: 1
  esp32_vflip: false
  esp32_hmirror: false
  esp32_pos_vflip: false
  esp32_pos_hmirror: false
  esp32_pos_aec_value: -1
  esp32_pos_agc_gain: 8
  esp32_pos_brightness: 0
  esp32_pos_contrast: 0
  esp32_capture_aec_value: -1
  esp32_capture_agc_gain: 8
  esp32_capture_brightness: 0
  esp32_capture_contrast: 0
  mqtt_host: localhost
  mqtt_port: 1883
  mqtt_user: mqtt
  mqtt_password: ""
  mqtt_client_id: "hydrometer-ocr-homeassistant"
  mqtt_topic_reading: hydrometer/reading
  addon_db_dir: "/config"
  addon_storage_dir: "/data/storage"
  addon_www_dir: "/config/www/hydrometer"
  addon_test_mode: false
  addon_ha_url: "http://homeassistant:8123"
  addon_ha_token: ""
  addon_ha_switch: ""
  addon_switch_on_off: True

schema:
  openai_api_key: password
  openai_model_default: str
  openai_model_secondary: str
  openai_require_consensus: bool
  ocr_entity_id: str
  ocr_digits: int
  ocr_max_delta_liters: int
  ocr_enable_heuristics: bool
  esp32_server: str
  esp32_capture_interval_min: int
  esp32_pre_capture_wait_ms: int
  esp32_capture_interval_ms: int
  esp32_delay_flash_ms: int
  framesize: str
  jpeg_quality: int
  fb_count: int
  esp32_vflip: bool
  esp32_hmirror: bool
  esp32_pos_vflip: bool
  esp32_pos_hmirror: bool
  esp32_pos_aec_value: int
  esp32_pos_agc_gain: int
  esp32_pos_brightness: int
  esp32_pos_contrast: int
  esp32_capture_aec_value: int
  esp32_capture_agc_gain: int
  esp32_capture_brightness: int
  esp32_capture_contrast: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  mqtt_client_id: str
  mqtt_topic_reading: str
  addon_db_dir: str
  addon_storage_dir: str
  addon_www_dir: str
  addon_test_mode: bool
  addon_ha_url: str
  addon_ha_token: str
  addon_ha_switch: str
  addon_switch_on_off: bool
